### ISSUE TITLE
Whats the trigger word?

### ISSUE THREAD

**Issue by vijayvammi** [erik/alexacast#3]
Hi Erik,

Thanks a lot for the detailed instruction but I am somehow missing something. I was able to install the alexacast on my Pi and connect my Pi to Chromecast too. 

But I dont know whats my trigger word or how to set it up. Can you please let me know on that?

Thanks
Vijay

**Comment by vijayvammi** [comment]
Hey Erik,

As usual, I found the answer after I posted the question. I am still setting up ssl certs and all that good stuff, will bug you if I cant succeed. 

Thanks
Vijay

**Comment by erik** [comment]
Hah, no worries. I've been wanting to write better instructions for setting this project up, since I know it is pretty vague right now, but I don't have an Alexa device handy anymore to confirm that everything works as expected.

I would actually really appreciate it if you typed up the steps that you ended up taking to set this up. I'm sure it would help a bunch of people.

**Comment by erik** [comment]
Closing for now, feel free to open another issue if you run into anything!

**Comment by vijayvammi** [comment]
Thanks Eric. I will gladly write a detailed instructions on setting up this one once I complete my set-up.
