### ISSUE TITLE
Is it possible to use this skill together with other player skills?

### ISSUE THREAD

**Issue by yurijmikhalevich** [erik/alexacast#4]
Hi.

Can I use it with Gee Music alexa skill?

https://github.com/stevenleeg/geemusic

**Comment by erik** [comment]
Hey Yurij!

So it seems GeeMusic is focused on playing google music on the alexa device itself, where alexacast is just a remote control for music on a chromecast. 

Unfortunately I won't be able to verify this myself, but in theory, if GeeMusic could cast to some chromecast device, the two projects would play nicely with each other, since Alexacast does support google play music.

Hopefully this helps!

**Comment by yurijmikhalevich** [comment]
Now I see. Thank you.
